//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerUser()
        {
            this.TradeOffer = new HashSet<TradeOffer>();
        }
    
        public long SteamID { get; set; }
        public string TradeURL { get; set; }
        public string UserName { get; set; }
        public string Avatar { get; set; }
        public System.DateTime Registered { get; set; }
        public bool Banned { get; set; }
        public System.DateTime LastTimeActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradeOffer> TradeOffer { get; set; }
    }
}
