//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TradingSiteEntities : DbContext
    {
        public TradingSiteEntities()
            : base("name=TradingSiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlacklistedItem> BlacklistedItem { get; set; }
        public virtual DbSet<Bot> Bot { get; set; }
        public virtual DbSet<Condition> Condition { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItemPrice> ItemPrice { get; set; }
        public virtual DbSet<Rarity> Rarity { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TemporaryUser> TemporaryUser { get; set; }
        public virtual DbSet<TradeOffer> TradeOffer { get; set; }
        public virtual DbSet<TradeOfferStatus> TradeOfferStatus { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<CustomerUser> CustomerUser { get; set; }
    }
}
